# Pandas 学习

***Pandas***
#### Panel Data

特点：
> 快速高效的DataFrame对象，具有默认和自定义的索引。
将数据从不同文件格式加载到内存中的数据对象的工具。
丢失数据的数据对齐和综合处理。
重组和摆动日期集。
基于标签的切片，索引和大数据集的子集。
可以删除或插入来自数据结构的列。
按数据分组进行聚合和转换。
高性能合并和数据加入。时间序列功能。

Pandas
Series由列构成（index）

DataFrame 由行列构成（index、）

Panel （行、列、页）

数据结构

- Series  一维数据结构
- DataFrame 二位数据结构
- Panel   三维数据结构


操作

1. 导入数据
  pd.DataFrame(pd.read_csv('.csv',))

In [27]:
import pandas as pd
import numpy as np

# 构建Series

a  =  pd.Series(np.arange(3),index=['a','b','c'])

print(a.dtype)
print(a.index)
a['b']

'b' in a

dic = {'a':'sb','b':'sda','c':1000}
b = pd.Series(dic)

b['a'] = 12
b['d'] = 1000

b
print(b['d'])

int32
Index(['a', 'b', 'c'], dtype='object')
1000

In [56]:
# 构建DataFrame

df = pd.DataFrame(np.arange(10).reshape(2,5),index = ['a','b'],columns=[4,5,6,7,8])

# 基本属性
#
print(df.columns)
print(df.index)
print(type(df.values))

print(df.shape)
print(df.dtypes)


# 常见操作
print(df.describe())

print(df.head(1)) # 看前1行的数据
print(df.tail(1))

print(df.sample(n = 1)) # 随机取3行



#  
df.sort_index(axis=1)
df

df = pd.DataFrame(pd.read_csv('./dataset/cleveland.csv',header = None))

df = df.head(10)
df.shape

# 删除某行
df.drop(9,axis=0)
# 删除列
df.drop(0,axis=1)



# 索引切片

#loc 函数 location  类似于list的slice 通过label索引
print(df.loc[3:5,(3,5,7)]) # 行 + 列

#iloc index location 通过行列号索引

# 访问单个元素 at
print(df.at[5,5])

# 访问某一列
print(df[5])


# 计算
# max、min、mean、std、count、median，cumsum、sum、diff
print(df[3][5])  # 3列5行
# 补全缺失值
df.fillna(value = 'error')  # method参数 ffill bfill  （forword fill

df

Int64Index([4, 5, 6, 7, 8], dtype='int64')
Index(['a', 'b'], dtype='object')
<class 'numpy.ndarray'>
(2, 5)
4    int32
5    int32
6    int32
7    int32
8    int32
dtype: object
              4         5         6         7         8
count  2.000000  2.000000  2.000000  2.000000  2.000000
mean   2.500000  3.500000  4.500000  5.500000  6.500000
std    3.535534  3.535534  3.535534  3.535534  3.535534
min    0.000000  1.000000  2.000000  3.000000  4.000000
25%    1.250000  2.250000  3.250000  4.250000  5.250000
50%    2.500000  3.500000  4.500000  5.500000  6.500000
75%    3.750000  4.750000  5.750000  6.750000  7.750000
max    5.000000  6.000000  7.000000  8.000000  9.000000
   4  5  6  7  8
a  0  1  2  3  4
   4  5  6  7  8
b  5  6  7  8  9
   4  5  6  7  8
b  5  6  7  8  9
       3    5      7
3  130.0  0.0  187.0
4  130.0  0.0  172.0
5  120.0  0.0  178.0
0.0
0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    1.0
Name: 5, dtype: float64
120.0

     0    1    2      3      4    5    6      7    8    9    10   11   12  13
0  63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0   0
1  67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0   2
2  67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0   1
3  37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0   0
4  41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0   0
5  56.0  1.0  2.0  120.0  236.0  0.0  0.0  178.0  0.0  0.8  1.0  0.0  3.0   0
6  62.0  0.0  4.0  140.0  268.0  0.0  2.0  160.0  0.0  3.6  3.0  2.0  3.0   3
7  57.0  0.0  4.0  120.0  354.0  0.0  0.0  163.0  1.0  0.6  1.0  0.0  3.0   0
8  63.0  1.0  4.0  130.0  254.0  0.0  2.0  147.0  0.0  1.4  2.0  1.0  7.0   2
9  53.0  1.0  4.0  140.0  203.0  1.0  2.0  155.0  1.0  3.1  3.0  0.0  7.0   1